sonar.projectKey=cerveceria-laravel
sonar.projectName=Cerveceria Laravel
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=vendor/**, node_modules/**, .scannerwork/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_c1a649c86442069e1fc9f3bb8eb20775239fb2ef